services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts-db:
    image: mysql
    container_name: accounts-db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounts
    extends:
      file: common-config.yml
      service: microservice-base-config

  config-server:
    build: ./configserver
    ports:
      - "8071:8071"
    container_name: config-server
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-base-config


  accounts:
    build: ./accounts
    ports:
      - "8999:8999"
    container_name: accounts
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"
    extends:
      file: common-config.yml
      service: microservice-base-config

  cards:
    build: ./cards
    ports:
      - "8998:8998"
    container_name: cards
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"
      SPRING_RABBITMQ_HOST: "rabbitmq"
    extends:
      file: common-config.yml
      service: microservice-base-config

  loans:
    build: ./loans
    ports:
      - "8997:8997"
    container_name: loans
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"
      SPRING_RABBITMQ_HOST: "rabbitmq"
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  backend:
    driver: bridge