services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts-db:
    container_name: accounts-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accounts
    extends:
      file: common-config.yml
      service: microservice-database-config

  cards-db:
    container_name: cards-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cards
    extends:
      file: common-config.yml
      service: microservice-database-config

  loans-db:
    container_name: loans-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loans
    extends:
      file: common-config.yml
      service: microservice-database-config

  config-server:
    build: ./configserver
    ports:
      - "8071:8071"
    container_name: config-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-base-config


  accounts:
    build: ./accounts
    ports:
      - "8999:8999"
    container_name: accounts
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: jdbc:mysql://accounts-db:3306/accounts
    depends_on:
      accounts-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-config-server-config

  cards:
    build: ./cards
    ports:
      - "8998:8998"
    container_name: cards
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: jdbc:mysql://cards-db:3306/cards
    depends_on:
      cards-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-config-server-config

  loans:
    build: ./loans
    ports:
      - "8997:8997"
    container_name: loans
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: jdbc:mysql://loans-db:3306/loans
    depends_on:
      loans-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-config-server-config

networks:
  backend:
    driver: bridge