server:
  port: 8072

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}"

spring:
  application:
    name: gatewayserver
  config:
    import: "${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: gatewayserver
    description: "Gateway Server"
    version: 1.0.0

logging:
  level:
    com:
      motivank:
        gatewayserver: DEBUG

# Resilience4j Circuit Breaker 설정
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10 # 몇 개의 호출을 기반으로 실패율을 계산할 것인지
        permitted-number-of-calls-in-half-open-state: 2 # Half open 상태에서 허용할 호출 수
        failure-rate-threshold: 50 # 실패율이 50% 이상이면 circuit open
        wait-duration-in-open-state: 10000 # circuit open 상태에서 대기할 시간