server:
  port: 8761

spring:
  application:
    name: eurekaserver
  config:
    import: "${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: "${EUREKA_INSTANCE_HOSTNAME:localhost}"
  client:
    fetch-registry: false
    register-with-eureka: false