server:
  port: 8999

spring:
  application:
    name: accounts
  profiles:
    active: prod
  config:
    import: "${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/accounts
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      init:
        mode: always
    properties:
      hibernate:
        format_sql: true
# circuit breaker on Feign client
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: accounts
    description: "Accounts Microservice"
    version: 1.0.0

logging:
  level:
    com:
      motivank:
        accounts: DEBUG

# Resilience4j Circuit Breaker 설정
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10 # 몇 개의 호출을 기반으로 실패율을 계산할 것인지
        permitted-number-of-calls-in-half-open-state: 2 # Half open 상태에서 허용할 호출 수
        failure-rate-threshold: 50 # 실패율이 50% 이상이면 circuit open
        wait-duration-in-open-state: 10000 # circuit open 상태에서 대기할 시간
  # Retry 설정
  retry:
    configs:
      default:
        max-attempts: 3 # 최대 재시도 횟수
        wait-duration: 100 # 재시도 전 대기 시간
        enable-exponential-backoff: true # 지수 백오프 활성화
        exponential-backoff-multiplier: 2 # 백오프 배수
        ignore-exceptions:
          - java.lang.NullPointerException # 무시할 예외
        retry-exceptions:
          - java.util.concurrent.TimeoutException # 재시도할 예외

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
