services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    extends:
      file: ../common-config.yml
      service: microservice-base-config

  accounts-db:
    container_name: accounts-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accounts
    extends:
      file: ../common-config.yml
      service: microservice-database-config

  cards-db:
    container_name: cards-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cards
    extends:
      file: ../common-config.yml
      service: microservice-database-config

  loans-db:
    container_name: loans-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loans
    extends:
      file: ../common-config.yml
      service: microservice-database-config

networks:
  backend:
    driver: bridge